package entitygen

import "text/template"

var funcMap = template.FuncMap{
	"snakeCase": snakeCase,
	"add":       func(a, b int) int { return a + b },
}

const serviceTemplate = `// Code generated by entitygen. DO NOT EDIT.

syntax = "proto3";

package {{.Package}};

import "{{.SourceFile}}";

option go_package = "{{.GoPackage}}";

// Create{{.Name}}Request is the request message for {{.Name}}Service.Create{{.Name}}.
message Create{{.Name}}Request {
  // The parent resource where the {{.Name}} will be created.
  string parent = 1;
{{range $i, $key := .SortedKeys}}
  // The {{$key.Name}} of the {{$.Name}} to create.
  {{$key.Type}} {{$key.Name}} = {{add 2 $i}};
{{end}}
  // The {{.Name}} resource to create.
  {{.Name}} {{.SnakeName}} = {{add 2 (len .SortedKeys)}};
}

// {{.Name}}Service provides CRUD operations for {{.Name}} entities.
service {{.Name}}Service {
  // Create{{.Name}} creates a new {{.Name}}.
  rpc Create{{.Name}}(Create{{.Name}}Request) returns ({{.Name}});
}
`

var serviceTmpl = template.Must(template.New("service").Funcs(funcMap).Parse(serviceTemplate))