package entitygen

import "text/template"

var funcMap = template.FuncMap{
	"snakeCase": snakeCase,
	"add":       func(a, b int) int { return a + b },
}

const serviceTemplate = `// Code generated by entitygen. DO NOT EDIT.

syntax = "proto3";

package {{.Package}};

import "{{.SourceFile}}";
{{- if .HasMethod "LIST"}}
import "proto/v1/query.proto";
{{- end}}

option go_package = "{{.GoPackage}}";
{{if .HasMethod "LIST"}}
// List{{.Name}}Response is the response message for {{.Name}}Service.List{{.Name}}.
message List{{.Name}}Response {
  // The list of {{.Name}} resources.
  repeated {{.Name}} {{.SnakeName}}s = 1;

  // A token, which can be sent as 'page_token' to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;

  // A token, which can be sent as 'page_token' to retrieve the previous page.
  // If this field is omitted, there are no previous pages.
  string prev_page_token = 3;

  // The total number of items, if requested.
  int64 total_size = 4;
}
{{end}}{{if .HasMethod "GET"}}
// Get{{.Name}}Request is the request message for {{.Name}}Service.Get{{.Name}}.
message Get{{.Name}}Request {
  // The name of the resource to retrieve.
  string name = 1;
}
{{end}}{{if .HasMethod "CREATE"}}
// Create{{.Name}}Request is the request message for {{.Name}}Service.Create{{.Name}}.
message Create{{.Name}}Request {
  // The parent resource where the {{.Name}} will be created.
  string parent = 1;
{{range $i, $key := .SortedKeys}}
  // The {{$key.Name}} of the {{$.Name}} to create.
  {{$key.Type}} {{$key.Name}} = {{add 2 $i}};
{{end}}
  // The {{.Name}} resource to create.
  {{.Name}} {{.SnakeName}} = {{add 2 (len .SortedKeys)}};
}
{{end}}
// {{.Name}}Service provides CRUD operations for {{.Name}} entities.
service {{.Name}}Service {
{{- if .HasMethod "GET"}}
  // Get{{.Name}} retrieves a {{.Name}} by its resource name.
  rpc Get{{.Name}}(Get{{.Name}}Request) returns ({{.Name}});
{{- end}}
{{- if .HasMethod "LIST"}}

  // List{{.Name}} lists {{.Name}} entities.
  rpc List{{.Name}}(gocrud.v1.ListRequest) returns (List{{.Name}}Response);
{{- end}}
{{- if .HasMethod "CREATE"}}

  // Create{{.Name}} creates a new {{.Name}}.
  rpc Create{{.Name}}(Create{{.Name}}Request) returns ({{.Name}});
{{- end}}
}
`

var serviceTmpl = template.Must(template.New("service").Funcs(funcMap).Parse(serviceTemplate))
