package crud

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"unicode"

	"github.com/FlorinBalint/gocrud/proto/entity"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/genproto/googleapis/type/date"
	"google.golang.org/genproto/googleapis/type/decimal"
	"google.golang.org/genproto/googleapis/type/timeofday"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// sqlRows is the interface for iterating over SQL result rows.
// *sql.Rows satisfies this interface.
type sqlRows interface {
	Next() bool
	Scan(dest ...any) error
	Close() error
	Err() error
}

// DBExecutor is an interface satisfied by *sql.DB, *sql.Tx, and mock executors.
type DBExecutor interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
}

// CreateHandler provides a generic implementation for creating entities in the database.
type CreateHandler[E proto.Message, Req proto.Message] struct {
	db      DBExecutor
	dialect sqldialect.Builder

	table      string
	columns    []string
	fieldByCol map[string]protoreflect.FieldDescriptor

	// autoGenPK is the single primary key field marked auto_generated, or nil.
	autoGenPK    protoreflect.FieldDescriptor
	autoGenPKCol string

	// autoGenFields are all fields marked auto_generated (including autoGenPK).
	// When the backend supports RETURNING, these columns are returned.
	autoGenFields []protoreflect.FieldDescriptor
	autoGenCols   []string

	// Reflection metadata for the request message
	entityField protoreflect.FieldDescriptor
	// reqIDFields are request fields matching non-auto-generated PKs.
	// The user must provide these.
	reqIDFields []protoreflect.FieldDescriptor

	// queryFn executes a query and returns rows. Defaults to db.QueryContext.
	// Overridable in tests to return mock rows.
	queryFn func(ctx context.Context, query string, args ...any) (sqlRows, error)
}

// NewCreateHandler initializes the handler, computing table names, column mappings,
// and validation rules once during startup.
func NewCreateHandler[E proto.Message, Req proto.Message](db DBExecutor, backend sqldialect.BackendType) (*CreateHandler[E, Req], error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, fmt.Errorf("initializing dialect: %w", err)
	}

	h := &CreateHandler[E, Req]{
		db:         db,
		dialect:    b,
		fieldByCol: make(map[string]protoreflect.FieldDescriptor),
	}
	h.queryFn = func(ctx context.Context, query string, args ...any) (sqlRows, error) {
		return db.QueryContext(ctx, query, args...)
	}

	// 1. Analyze the Entity message (E) using reflection
	var e E
	eType := reflect.TypeOf(e)
	if eType.Kind() != reflect.Ptr {
		return nil, fmt.Errorf("E must be a pointer type (e.g., *pb.User)")
	}
	entityMsg := reflect.New(eType.Elem()).Interface().(E)
	entityDesc := entityMsg.ProtoReflect().Descriptor()

	if ext := proto.GetExtension(entityDesc.Options(), entity.E_Table); ext != nil && ext.(string) != "" {
		h.table = ext.(string)
	} else {
		h.table = toSnakeCase(string(entityDesc.Name()))
	}

	var pkFields []protoreflect.FieldDescriptor
	fields := entityDesc.Fields()
	for i := 0; i < fields.Len(); i++ {
		f := fields.Get(i)
		colName := string(f.Name())
		if ext := proto.GetExtension(f.Options(), entity.E_DbColumn); ext != nil && ext.(string) != "" {
			colName = ext.(string)
		}

		h.columns = append(h.columns, colName)
		h.fieldByCol[colName] = f

		isPK := false
		if ext := proto.GetExtension(f.Options(), entity.E_PrimaryKey); ext != nil {
			if order, ok := ext.(int32); ok && order > 0 {
				isPK = true
				pkFields = append(pkFields, f)
			}
		}

		if autoGen, _ := proto.GetExtension(f.Options(), entity.E_AutoGenerated).(bool); autoGen {
			h.autoGenFields = append(h.autoGenFields, f)
			h.autoGenCols = append(h.autoGenCols, colName)

			if isPK {
				if h.autoGenPK != nil {
					return nil, fmt.Errorf("at most one primary key may be auto_generated, found both %q and %q", h.autoGenPK.Name(), f.Name())
				}
				h.autoGenPK = f
				h.autoGenPKCol = colName
			}
		}
	}

	// 2. Analyze the Request message (Req)
	var req Req
	reqType := reflect.TypeOf(req)
	if reqType.Kind() != reflect.Ptr {
		return nil, fmt.Errorf("Req must be a pointer type (e.g., *pb.CreateUserRequest)")
	}
	reqMsg := reflect.New(reqType.Elem()).Interface().(Req)
	reqDesc := reqMsg.ProtoReflect().Descriptor()

	reqFields := reqDesc.Fields()
	for i := 0; i < reqFields.Len(); i++ {
		f := reqFields.Get(i)
		if f.Kind() == protoreflect.MessageKind && f.Message().FullName() == entityDesc.FullName() {
			h.entityField = f
		}

		// Track request fields that match non-auto-generated PKs.
		for _, pk := range pkFields {
			if f.Name() == pk.Name() && pk != h.autoGenPK {
				h.reqIDFields = append(h.reqIDFields, f)
			}
		}
	}

	if h.entityField == nil {
		return nil, fmt.Errorf("request message %s does not contain entity field of type %s", reqDesc.FullName(), entityDesc.FullName())
	}

	return h, nil
}

// Create handles the incoming request, validates required IDs, parses values into
// an InsertQuery, and executes it.
func (h *CreateHandler[E, Req]) Create(ctx context.Context, req Req) (E, error) {
	entity, err := h.extractEntity(req)
	if err != nil {
		var zero E
		return zero, err
	}

	if err := h.validateAndCopyIDs(req, entity); err != nil {
		var zero E
		return zero, err
	}

	sqlStr, args, err := h.buildInsert(entity)
	if err != nil {
		var zero E
		return zero, status.Errorf(codes.Internal, "building sql: %v", err)
	}

	if err := h.executeInsert(ctx, entity, sqlStr, args); err != nil {
		var zero E
		return zero, err
	}

	return entity, nil
}

func (h *CreateHandler[E, Req]) extractEntity(req Req) (E, error) {
	reqReflect := req.ProtoReflect()
	if !reqReflect.Has(h.entityField) {
		var zero E
		return zero, status.Errorf(codes.InvalidArgument, "missing entity field in request")
	}
	return reqReflect.Get(h.entityField).Message().Interface().(E), nil
}

func (h *CreateHandler[E, Req]) validateAndCopyIDs(req Req, entity E) error {
	reqReflect := req.ProtoReflect()
	entityVal := entity.ProtoReflect()

	for _, reqIDField := range h.reqIDFields {
		if !reqReflect.Has(reqIDField) && isZeroValue(reqReflect.Get(reqIDField)) {
			return status.Errorf(codes.InvalidArgument, "missing required ID field: %s", reqIDField.Name())
		}

		idVal := reqReflect.Get(reqIDField)
		entityIDField := entityVal.Descriptor().Fields().ByName(reqIDField.Name())
		if entityIDField != nil {
			entityVal.Set(entityIDField, idVal)
		}
	}
	return nil
}

func (h *CreateHandler[E, Req]) buildInsert(entity E) (string, []any, error) {
	entityVal := entity.ProtoReflect()
	values := make([]*gocrudv1.Value, len(h.columns))

	for i, col := range h.columns {
		f := h.fieldByCol[col]
		if !entityVal.Has(f) && isZeroValue(entityVal.Get(f)) {
			values[i] = nil // SQL DEFAULT
			continue
		}
		values[i] = protoValueToSQLValue(f, entityVal.Get(f))
	}

	var returningCols []string
	if len(h.autoGenCols) > 0 && h.dialect.SupportsReturning() {
		returningCols = h.autoGenCols
	}

	q := sqldialect.NewInsertQuery(h.table, h.columns, values, returningCols)
	sqlStr, args, err := h.dialect.BuildInsert(q)
	return sqlStr, args, err
}

func (h *CreateHandler[E, Req]) executeInsert(ctx context.Context, entity E, sqlStr string, args []any) error {
	if len(h.autoGenFields) > 0 && h.dialect.SupportsReturning() {
		rows, err := h.queryFn(ctx, sqlStr, args...)
		if err != nil {
			return status.Errorf(codes.Internal, "executing insert query: %v", err)
		}
		return scanReturning(rows, entity.ProtoReflect(), h.autoGenFields)
	}

	res, err := h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return status.Errorf(codes.Internal, "executing insert: %v", err)
	}

	// Without RETURNING, we can only recover the auto-generated PK via LastInsertId.
	if h.autoGenPK != nil {
		setLastInsertID(entity.ProtoReflect(), res, h.autoGenPK)
	}

	return nil
}

// scanReturning reads auto-generated field values from a RETURNING result set
// and sets them on the entity.
func scanReturning(rows sqlRows, entityVal protoreflect.Message, fields []protoreflect.FieldDescriptor) error {
	defer rows.Close()

	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return status.Errorf(codes.Internal, "reading returning rows: %v", err)
		}
		return status.Errorf(codes.Internal, "insert did not return any rows")
	}

	dest := make([]any, len(fields))
	for i, f := range fields {
		switch f.Kind() {
		case protoreflect.StringKind:
			dest[i] = new(string)
		case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind:
			dest[i] = new(int64)
		default:
			return status.Errorf(codes.Internal, "unsupported returning field kind: %v", f.Kind())
		}
	}

	if err := rows.Scan(dest...); err != nil {
		return status.Errorf(codes.Internal, "scanning returning values: %v", err)
	}

	for i, f := range fields {
		switch f.Kind() {
		case protoreflect.StringKind:
			entityVal.Set(f, protoreflect.ValueOfString(*(dest[i].(*string))))
		case protoreflect.Int32Kind:
			entityVal.Set(f, protoreflect.ValueOfInt32(int32(*(dest[i].(*int64)))))
		case protoreflect.Int64Kind:
			entityVal.Set(f, protoreflect.ValueOfInt64(*(dest[i].(*int64))))
		case protoreflect.Uint32Kind:
			entityVal.Set(f, protoreflect.ValueOfUint32(uint32(*(dest[i].(*int64)))))
		case protoreflect.Uint64Kind:
			entityVal.Set(f, protoreflect.ValueOfUint64(uint64(*(dest[i].(*int64)))))
		}
	}
	return nil
}

// setLastInsertID attempts to populate the auto-generated PK from sql.Result.LastInsertId.
// Used by backends like MySQL that don't support RETURNING.
func setLastInsertID(entityVal protoreflect.Message, res sql.Result, pk protoreflect.FieldDescriptor) {
	id, err := res.LastInsertId()
	if err != nil || id <= 0 {
		return
	}
	switch pk.Kind() {
	case protoreflect.Int32Kind:
		entityVal.Set(pk, protoreflect.ValueOfInt32(int32(id)))
	case protoreflect.Int64Kind:
		entityVal.Set(pk, protoreflect.ValueOfInt64(id))
	case protoreflect.Uint32Kind:
		entityVal.Set(pk, protoreflect.ValueOfUint32(uint32(id)))
	case protoreflect.Uint64Kind:
		entityVal.Set(pk, protoreflect.ValueOfUint64(uint64(id)))
	}
}

// Helper: Convert proto value to gocrudv1.Value
func protoValueToSQLValue(fd protoreflect.FieldDescriptor, val protoreflect.Value) *gocrudv1.Value {
	switch fd.Kind() {
	case protoreflect.StringKind:
		return &gocrudv1.Value{Kind: &gocrudv1.Value_StringValue{StringValue: val.String()}}
	case protoreflect.Int64Kind, protoreflect.Int32Kind, protoreflect.Uint64Kind, protoreflect.Uint32Kind:
		return &gocrudv1.Value{Kind: &gocrudv1.Value_IntValue{IntValue: val.Int()}}
	case protoreflect.DoubleKind, protoreflect.FloatKind:
		return &gocrudv1.Value{Kind: &gocrudv1.Value_DoubleValue{DoubleValue: val.Float()}}
	case protoreflect.BoolKind:
		return &gocrudv1.Value{Kind: &gocrudv1.Value_BoolValue{BoolValue: val.Bool()}}
	case protoreflect.BytesKind:
		return &gocrudv1.Value{Kind: &gocrudv1.Value_BytesValue{BytesValue: val.Bytes()}}
	case protoreflect.MessageKind:
		msgName := fd.Message().FullName()
		msgIface := val.Message().Interface()
		switch msgName {
		case "google.protobuf.Timestamp":
			if ts, ok := msgIface.(*timestamppb.Timestamp); ok {
				return &gocrudv1.Value{Kind: &gocrudv1.Value_TimestampValue{TimestampValue: ts}}
			}
		case "google.protobuf.Duration":
			if d, ok := msgIface.(*durationpb.Duration); ok {
				return &gocrudv1.Value{Kind: &gocrudv1.Value_IntervalValue{IntervalValue: d}}
			}
		case "google.type.Date":
			if d, ok := msgIface.(*date.Date); ok {
				return &gocrudv1.Value{Kind: &gocrudv1.Value_DateValue{DateValue: d}}
			}
		case "google.type.TimeOfDay":
			if t, ok := msgIface.(*timeofday.TimeOfDay); ok {
				return &gocrudv1.Value{Kind: &gocrudv1.Value_TimeValue{TimeValue: t}}
			}
		case "google.type.Decimal":
			if dec, ok := msgIface.(*decimal.Decimal); ok {
				return &gocrudv1.Value{Kind: &gocrudv1.Value_DecimalValue{DecimalValue: dec}}
			}
		}
	}
	return nil
}

// Helper: Check if a value is the proto3 default (zero value)
func isZeroValue(val protoreflect.Value) bool {
	switch val.Interface().(type) {
	case string:
		return val.String() == ""
	case int32, int64, uint32, uint64:
		return val.Int() == 0
	case float32, float64:
		return val.Float() == 0
	case bool:
		return !val.Bool()
	case []byte:
		return len(val.Bytes()) == 0
	}
	return false
}

// Helper: Convert CamelCase to snake_case for default table names
func toSnakeCase(s string) string {
	var sb strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) {
			if i > 0 {
				sb.WriteByte('_')
			}
			sb.WriteRune(unicode.ToLower(r))
		} else {
			sb.WriteRune(r)
		}
	}
	return sb.String()
}
