load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sqldialect",
    srcs = [
        "builder.go",
        "common.go",
        "mysql.go",
        "postgres.go",
    ],
    importpath = "github.com/FlorinBalint/gocrud/sqldialect",
    visibility = ["//visibility:public"],
    deps = [
        "//proto/v1:query_go_proto",
    ],
)

go_test(
    name = "sqldialect_test",
    srcs = [
        "mysql_test.go",
        "postgres_test.go",
    ],
    embed = [":sqldialect"],
    deps = [
        "//proto/v1:query_go_proto",
        "@org_golang_google_genproto//googleapis/type/date",
        "@org_golang_google_genproto//googleapis/type/timeofday",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
