load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

filegroup(
    name = "test_files",
    srcs = glob(["*.proto"]),
    visibility = ["//visibility:public"],
)

proto_library(
    name = "testdata_proto",
    srcs = [
        "entities.proto",
        "audit_log_service.proto",
        "autogen_user_service.proto",
        "checkpoint_service.proto",
        "delete_only_service.proto",
        "get_only_service.proto",
        "list_upsert_delete_with_etag_service.proto",
        "options_override_service.proto",
        "realuser_service.proto",
        "upsert_only_service.proto",
        "event_service.proto",
        "product_service.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//proto/entity:options_proto",
        "//proto/v1:query_proto",
        "@googleapis//google/api:annotations_proto",
        "@googleapis//google/api:client_proto",
        "@googleapis//google/api:field_behavior_proto",
        "@googleapis//google/api:resource_proto",
        "@googleapis//google/type:date_proto",
        "@googleapis//google/type:decimal_proto",
        "@googleapis//google/type:timeofday_proto",
        "@protobuf//:duration_proto",
        "@protobuf//:empty_proto",
        "@protobuf//:field_mask_proto",
        "@protobuf//:timestamp_proto",
    ],
)

go_proto_library(
    name = "testdata_go_proto",
    importpath = "github.com/FlorinBalint/gocrud/entitygen/testdata",
    proto = ":testdata_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//proto/entity:options_go_proto",
        "//proto/v1:query_go_proto",
        "@googleapis//google/api:annotations_go_proto",
        "@org_golang_google_genproto//googleapis/type/date",
        "@org_golang_google_genproto//googleapis/type/decimal",
        "@org_golang_google_genproto//googleapis/type/timeofday",
    ],
)
