syntax = "proto3";

package testdata.v1;

option go_package = "github.com/FlorinBalint/gocrud/entitygen/testdata;testdata";

import "proto/entity/options.proto";

message RealUser {
  option (gocrud.entity.entity) = true;

  string id = 1 [(gocrud.entity.primary_key) = 1];
  string email = 2;
}

message CreateOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = CREATE;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message GetOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = GET;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message ListOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = LIST;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message UpdateOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = UPDATE;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message UpdateWithEtagUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = UPDATE;
  option (gocrud.entity.has_etag) = true;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message UpsertOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = UPSERT;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message DeleteOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = DELETE;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message ListUpsertDeleteWithEtagUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = LIST;
  option (gocrud.entity.methods) = UPSERT;
  option (gocrud.entity.methods) = DELETE;
  option (gocrud.entity.has_etag) = true;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message OptionsOverrideUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.resource_path) = "/api/v2/accounts/{account_id}/custom_users/{id}";
  option (gocrud.entity.resource_type) = "custom.googleapis.com/CustomUser";

  string account_id = 1 [(gocrud.entity.primary_key) = 1];
  string id = 2 [(gocrud.entity.primary_key) = 2];
}

message AutogenUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.table) = "composite_entities";
  option (gocrud.entity.resource_type) = "custom.googleapis.com/CustomUser";

  string id_1 = 1 [(gocrud.entity.primary_key) = 1];

  int64 id_2 = 2 [
    (gocrud.entity.primary_key) = 2
  ];

  int64 id_3 = 3 [
    (gocrud.entity.primary_key) = 2,
    (gocrud.entity.auto_generated) = true
  ];
  
  string email = 4;
}