syntax = "proto3";

package testdata.v1;

option go_package = "github.com/FlorinBalint/gocrud/entitygen/testdata;testdata";

import "proto/entity/options.proto";

message RealUser {
  option (gocrud.entity.entity) = true;

  string id = 1 [(gocrud.entity.primary_key) = 1];
  string email = 2;
}

message CreateOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = CREATE;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message GetOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = GET;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message ListOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = LIST;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message UpdateOnlyUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = UPDATE;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}

message UpdateWithEtagUser {
  option (gocrud.entity.entity) = true;
  option (gocrud.entity.methods) = UPDATE;
  option (gocrud.entity.has_etag) = true;

  string id = 1 [(gocrud.entity.primary_key) = 1];
}