// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// RealUserCreateHandler handles Create requests for RealUser entities.
type RealUserCreateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewRealUserCreateHandler creates a new handler for creating RealUser entities.
func NewRealUserCreateHandler(db DBExecutor, backend sqldialect.BackendType) (*RealUserCreateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &RealUserCreateHandler{db: db, dialect: b}, nil
}

// Create handles a CreateRealUserRequest and returns the created RealUser.
func (h *RealUserCreateHandler) Create(ctx context.Context, req *testdata.CreateRealUserRequest) (*testdata.RealUser, error) {
	entity := req.GetRealUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing RealUser in request")
	}

	// Copy provided keys from request to entity.
	if req.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required ID field: id")
	}
	entity.Id = req.GetId()

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"id", "email"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetId()),
		stringValue(entity.GetEmail()),
	}
	var returningCols []string
	q := sqldialect.NewInsertQuery("real_user", columns, values, returningCols)
	sqlStr, args, err := h.dialect.BuildInsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building insert SQL: %v", err)
	}
	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing insert: %v", err)
	}
	return entity, nil
}
