// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"database/sql"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/timestamppb"
	"time"
)

// AuditLogCreateHandler handles Create requests for AuditLog entities.
type AuditLogCreateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewAuditLogCreateHandler creates a new handler for creating AuditLog entities.
func NewAuditLogCreateHandler(db DBExecutor, backend sqldialect.BackendType) (*AuditLogCreateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &AuditLogCreateHandler{db: db, dialect: b}, nil
}

// Create handles a CreateAuditLogRequest and returns the created AuditLog.
func (h *AuditLogCreateHandler) Create(ctx context.Context, req *testdata.CreateAuditLogRequest) (*testdata.AuditLog, error) {
	entity := req.GetAuditLog()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing AuditLog in request")
	}

	// Copy provided keys from request to entity.
	if req.GetTraceId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required ID field: trace_id")
	}
	entity.TraceId = req.GetTraceId()

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"trace_id", "action"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetTraceId()),
		stringValue(entity.GetAction()),
	}
	var returningCols []string
	if h.dialect.SupportsReturning() {
		returningCols = []string{"created_at"}
	}
	q := sqldialect.NewInsertQuery("audit_log", columns, values, returningCols)
	sqlStr, args, err := h.dialect.BuildInsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building insert SQL: %v", err)
	}
	var autoGen0 time.Time
	err = execInsertAndScan(ctx, h.db, h.dialect.SupportsReturning(),
		sqlStr, args,
		func(lastInsertId int64) (string, []any, error) {
			selectCols := []string{"created_at"}
			filter := h.primaryKeyFilter(entity)
			selQ := sqldialect.NewSelectQuery("audit_log", selectCols, filter, nil, 1, 0, false)
			return h.dialect.BuildSelect(selQ)
		},
		func(row RowScanner) error {
			return row.Scan(&autoGen0)
		},
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, status.Errorf(codes.Internal, "insert did not return any rows")
		}
		return nil, status.Errorf(codes.Internal, "executing insert/select: %v", err)
	}
	// Set auto-generated values on the entity.
	entity.CreatedAt = timestamppb.New(autoGen0)
	return entity, nil
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *AuditLogCreateHandler) primaryKeyFilter(entity *testdata.AuditLog) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Condition{
			Condition: &gocrudv1.Condition{
				Column:  "trace_id",
				Op:      gocrudv1.Operator_EQUAL,
				Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetTraceId())},
			},
		},
	}
}
