// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// EventCreateHandler handles Create requests for Event entities.
type EventCreateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewEventCreateHandler creates a new handler for creating Event entities.
func NewEventCreateHandler(db DBExecutor, backend sqldialect.BackendType) (*EventCreateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &EventCreateHandler{db: db, dialect: b}, nil
}

// Create handles a CreateEventRequest and returns the created Event.
func (h *EventCreateHandler) Create(ctx context.Context, req *testdata.CreateEventRequest) (*testdata.Event, error) {
	entity := req.GetEvent()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing Event in request")
	}

	// Copy provided keys from request to entity.
	if req.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required ID field: id")
	}
	entity.Id = req.GetId()
	if req.GetCommitTimestamp() == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing required ID field: commit_timestamp")
	}
	entity.CommitTimestamp = req.GetCommitTimestamp()

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"id", "commit_timestamp", "date_of_birth", "duration", "price", "alarm_time"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetId()),
		timestampValue(entity.GetCommitTimestamp()),
		dateValue(entity.GetDateOfBirth()),
		durationValue(entity.GetDuration()),
		decimalValue(entity.GetPrice()),
		timeOfDayValue(entity.GetAlarmTime()),
	}
	var returningCols []string
	q := sqldialect.NewInsertQuery("event", columns, values, returningCols)
	sqlStr, args, err := h.dialect.BuildInsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building insert SQL: %v", err)
	}
	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing insert: %v", err)
	}
	return entity, nil
}
