// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// OptionsOverrideUserCreateHandler handles Create requests for OptionsOverrideUser entities.
type OptionsOverrideUserCreateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewOptionsOverrideUserCreateHandler creates a new handler for creating OptionsOverrideUser entities.
func NewOptionsOverrideUserCreateHandler(db DBExecutor, backend sqldialect.BackendType) (*OptionsOverrideUserCreateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &OptionsOverrideUserCreateHandler{db: db, dialect: b}, nil
}

// Create handles a CreateOptionsOverrideUserRequest and returns the created OptionsOverrideUser.
func (h *OptionsOverrideUserCreateHandler) Create(ctx context.Context, req *testdata.CreateOptionsOverrideUserRequest) (*testdata.OptionsOverrideUser, error) {
	entity := req.GetOptionsOverrideUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing OptionsOverrideUser in request")
	}

	// Copy provided keys from request to entity.
	if req.GetAccountId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required ID field: account_id")
	}
	entity.AccountId = req.GetAccountId()
	if req.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required ID field: id")
	}
	entity.Id = req.GetId()

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"account_id", "id"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetAccountId()),
		stringValue(entity.GetId()),
	}
	var returningCols []string
	q := sqldialect.NewInsertQuery("options_override_user", columns, values, returningCols)
	sqlStr, args, err := h.dialect.BuildInsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building insert SQL: %v", err)
	}
	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing insert: %v", err)
	}
	return entity, nil
}
