// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ProductCreateHandler handles Create requests for Product entities.
type ProductCreateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewProductCreateHandler creates a new handler for creating Product entities.
func NewProductCreateHandler(db DBExecutor, backend sqldialect.BackendType) (*ProductCreateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &ProductCreateHandler{db: db, dialect: b}, nil
}

// Create handles a CreateProductRequest and returns the created Product.
func (h *ProductCreateHandler) Create(ctx context.Context, req *testdata.CreateProductRequest) (*testdata.Product, error) {
	entity := req.GetProduct()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing Product in request")
	}

	// Copy provided keys from request to entity.
	if req.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required ID field: id")
	}
	entity.Id = req.GetId()

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"id", "name", "description", "price", "quantity", "available", "updated_at"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetId()),
		stringValue(entity.GetName()),
		stringValue(entity.GetDescription()),
		decimalValue(entity.GetPrice()),
		intValue(entity.GetQuantity()),
		boolValue(entity.GetAvailable()),
		timestampValue(entity.GetUpdatedAt()),
	}
	var returningCols []string
	q := sqldialect.NewInsertQuery("product", columns, values, returningCols)
	sqlStr, args, err := h.dialect.BuildInsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building insert SQL: %v", err)
	}
	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing insert: %v", err)
	}
	return entity, nil
}
