// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"

	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// AutogenUserCreateHandler handles Create requests for AutogenUser entities.
type AutogenUserCreateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewAutogenUserCreateHandler creates a new handler for creating AutogenUser entities.
func NewAutogenUserCreateHandler(db DBExecutor, backend sqldialect.BackendType) (*AutogenUserCreateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &AutogenUserCreateHandler{db: db, dialect: b}, nil
}

// Create handles a CreateAutogenUserRequest and returns the created AutogenUser.
func (h *AutogenUserCreateHandler) Create(ctx context.Context, req *testdata.CreateAutogenUserRequest) (*testdata.AutogenUser, error) {
	entity := req.GetAutogenUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing AutogenUser in request")
	}

	// Copy provided keys from request to entity.
	if req.GetId_1() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required ID field: id_1")
	}
	entity.Id_1 = req.GetId_1()
	if req.GetId_2() == 0 {
		return nil, status.Errorf(codes.InvalidArgument, "missing required ID field: id_2")
	}
	entity.Id_2 = req.GetId_2()

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"id_1", "id_2", "email"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetId_1()),
		intValue(entity.GetId_2()),
		stringValue(entity.GetEmail()),
	}

	// RETURNING for auto-generated columns.
	var returningCols []string
	if h.dialect.SupportsReturning() {
		returningCols = []string{"id_3"}
	}

	q := sqldialect.NewInsertQuery("composite_entities", columns, values, returningCols)
	sqlStr, args, err := h.dialect.BuildInsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building insert SQL: %v", err)
	}

	if h.dialect.SupportsReturning() {
		rows, err := h.db.QueryContext(ctx, sqlStr, args...)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "executing insert query: %v", err)
		}
		defer rows.Close()

		if !rows.Next() {
			if err := rows.Err(); err != nil {
				return nil, status.Errorf(codes.Internal, "reading returning rows: %v", err)
			}
			return nil, status.Errorf(codes.Internal, "insert did not return any rows")
		}

		// Scan auto-generated columns.
		var autoGen0 int64
		if err := rows.Scan(&autoGen0); err != nil {
			return nil, status.Errorf(codes.Internal, "scanning returning values: %v", err)
		}

		// Set auto-generated values on the entity.
		entity.Id_3 = autoGen0
	} else {
		res, err := h.db.ExecContext(ctx, sqlStr, args...)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "executing insert: %v", err)
		}

		// Without RETURNING, recover auto-generated PK via LastInsertId.
		if id, err := res.LastInsertId(); err == nil && id > 0 {
			entity.Id_3 = id
		}
	}

	return entity, nil
}
