// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"strconv"
	"strings"
)

// AutogenUserDeleteHandler handles Delete requests for AutogenUser entities.
type AutogenUserDeleteHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewAutogenUserDeleteHandler creates a new handler for deleting AutogenUser entities.
func NewAutogenUserDeleteHandler(db DBExecutor, backend sqldialect.BackendType) (*AutogenUserDeleteHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &AutogenUserDeleteHandler{db: db, dialect: b}, nil
}

// Delete handles a DeleteAutogenUserRequest and deletes the AutogenUser.
func (h *AutogenUserDeleteHandler) Delete(ctx context.Context, req *testdata.DeleteAutogenUserRequest) (*emptypb.Empty, error) {
	name := req.GetName()
	if name == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing resource name")
	}

	parts := strings.Split(strings.TrimPrefix(name, "/"), "/")
	if len(parts) != 6 {
		return nil, status.Errorf(codes.InvalidArgument, "invalid resource name %q: expected 6 path segments", name)
	}

	entity := &testdata.AutogenUser{}

	if parts[3] == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing id_1 in resource name: %q", name)
	}
	entity.Id_1 = parts[3]

	{
		v, err := strconv.ParseInt(parts[4], 10, 64)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid id_2 in resource name: %v", err)
		}
		entity.Id_2 = v
	}

	{
		v, err := strconv.ParseInt(parts[5], 10, 64)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid id_3 in resource name: %v", err)
		}
		entity.Id_3 = v
	}

	filter := h.primaryKeyFilter(entity)

	delQ := sqldialect.NewDeleteQuery("composite_entities", filter, nil)
	sqlStr, args, err := h.dialect.BuildDelete(delQ)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building delete SQL: %v", err)
	}

	res, err := h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "permission denied") ||
			strings.Contains(strings.ToLower(err.Error()), "access denied") {
			return nil, status.Errorf(codes.PermissionDenied, "permission denied: %v", err)
		}
		return nil, status.Errorf(codes.Internal, "deleting AutogenUser: %v", err)
	}

	if !req.GetAllowMissing() {
		n, err := res.RowsAffected()
		if err != nil {
			return nil, status.Errorf(codes.Internal, "checking rows affected: %v", err)
		}
		if n == 0 {
			return nil, status.Errorf(codes.NotFound, "AutogenUser %q not found", name)
		}
	}

	return &emptypb.Empty{}, nil
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *AutogenUserDeleteHandler) primaryKeyFilter(entity *testdata.AutogenUser) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Composite{
			Composite: &gocrudv1.CompositeFilter{
				Op: gocrudv1.CompositeFilter_AND,
				Filters: []*gocrudv1.Filter{
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id_1",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetId_1())},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id_2",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: intValue(entity.GetId_2())},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id_3",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: intValue(entity.GetId_3())},
							},
						},
					},
				},
			},
		},
	}
}
