// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"strings"
)

// RealUserDeleteHandler handles Delete requests for RealUser entities.
type RealUserDeleteHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewRealUserDeleteHandler creates a new handler for deleting RealUser entities.
func NewRealUserDeleteHandler(db DBExecutor, backend sqldialect.BackendType) (*RealUserDeleteHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &RealUserDeleteHandler{db: db, dialect: b}, nil
}

// Delete handles a DeleteRealUserRequest and deletes the RealUser.
func (h *RealUserDeleteHandler) Delete(ctx context.Context, req *testdata.DeleteRealUserRequest) (*emptypb.Empty, error) {
	name := req.GetName()
	if name == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing resource name")
	}

	parts := strings.Split(strings.TrimPrefix(name, "/"), "/")
	if len(parts) != 4 {
		return nil, status.Errorf(codes.InvalidArgument, "invalid resource name %q: expected 4 path segments", name)
	}

	entity := &testdata.RealUser{}

	if parts[3] == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing id in resource name: %q", name)
	}
	entity.Id = parts[3]

	filter := h.primaryKeyFilter(entity)

	delQ := sqldialect.NewDeleteQuery("real_user", filter, nil)
	sqlStr, args, err := h.dialect.BuildDelete(delQ)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building delete SQL: %v", err)
	}

	res, err := h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "permission denied") ||
			strings.Contains(strings.ToLower(err.Error()), "access denied") {
			return nil, status.Errorf(codes.PermissionDenied, "permission denied: %v", err)
		}
		return nil, status.Errorf(codes.Internal, "deleting RealUser: %v", err)
	}

	if !req.GetAllowMissing() {
		n, err := res.RowsAffected()
		if err != nil {
			return nil, status.Errorf(codes.Internal, "checking rows affected: %v", err)
		}
		if n == 0 {
			return nil, status.Errorf(codes.NotFound, "RealUser %q not found", name)
		}
	}

	return &emptypb.Empty{}, nil
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *RealUserDeleteHandler) primaryKeyFilter(entity *testdata.RealUser) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Condition{
			Condition: &gocrudv1.Condition{
				Column:  "id",
				Op:      gocrudv1.Operator_EQUAL,
				Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetId())},
			},
		},
	}
}
