// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"database/sql"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"strings"
)

// OptionsOverrideUserGetHandler handles Get requests for OptionsOverrideUser entities.
type OptionsOverrideUserGetHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewOptionsOverrideUserGetHandler creates a new handler for getting OptionsOverrideUser entities.
func NewOptionsOverrideUserGetHandler(db DBExecutor, backend sqldialect.BackendType) (*OptionsOverrideUserGetHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &OptionsOverrideUserGetHandler{db: db, dialect: b}, nil
}

// Get handles a GetOptionsOverrideUserRequest and returns the OptionsOverrideUser.
func (h *OptionsOverrideUserGetHandler) Get(ctx context.Context, req *testdata.GetOptionsOverrideUserRequest) (*testdata.OptionsOverrideUser, error) {
	name := req.GetName()
	if name == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing resource name")
	}

	parts := strings.Split(strings.TrimPrefix(name, "/"), "/")
	if len(parts) != 6 {
		return nil, status.Errorf(codes.InvalidArgument, "invalid resource name %q: expected 6 path segments", name)
	}

	entity := &testdata.OptionsOverrideUser{}

	if parts[3] == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing account_id in resource name: %q", name)
	}
	entity.AccountId = parts[3]

	if parts[5] == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing id in resource name: %q", name)
	}
	entity.Id = parts[5]

	filter := h.primaryKeyFilter(entity)

	selectCols := []string{"account_id", "id"}
	selQ := sqldialect.NewSelectQuery("options_override_user", selectCols, filter, nil, 1, 0, false)
	sqlStr, args, err := h.dialect.BuildSelect(selQ)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building select SQL: %v", err)
	}

	var checkPK0 string
	var checkPK1 string
	row := h.db.QueryRowContext(ctx, sqlStr, args...)
	if err := row.Scan(&checkPK0, &checkPK1); err != nil {
		if err == sql.ErrNoRows {
			return nil, status.Errorf(codes.NotFound, "OptionsOverrideUser %q not found", name)
		}
		if strings.Contains(strings.ToLower(err.Error()), "permission denied") ||
			strings.Contains(strings.ToLower(err.Error()), "access denied") {
			return nil, status.Errorf(codes.PermissionDenied, "permission denied: %v", err)
		}
		return nil, status.Errorf(codes.Internal, "querying OptionsOverrideUser: %v", err)
	}

	return entity, nil
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *OptionsOverrideUserGetHandler) primaryKeyFilter(entity *testdata.OptionsOverrideUser) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Composite{
			Composite: &gocrudv1.CompositeFilter{
				Op: gocrudv1.CompositeFilter_AND,
				Filters: []*gocrudv1.Filter{
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "account_id",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetAccountId())},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetId())},
							},
						},
					},
				},
			},
		},
	}
}
