// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"database/sql"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"strings"
)

// GetOnlyUserGetHandler handles Get requests for GetOnlyUser entities.
type GetOnlyUserGetHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewGetOnlyUserGetHandler creates a new handler for getting GetOnlyUser entities.
func NewGetOnlyUserGetHandler(db DBExecutor, backend sqldialect.BackendType) (*GetOnlyUserGetHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &GetOnlyUserGetHandler{db: db, dialect: b}, nil
}

// Get handles a GetGetOnlyUserRequest and returns the GetOnlyUser.
func (h *GetOnlyUserGetHandler) Get(ctx context.Context, req *testdata.GetGetOnlyUserRequest) (*testdata.GetOnlyUser, error) {
	name := req.GetName()
	if name == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing resource name")
	}

	parts := strings.Split(strings.TrimPrefix(name, "/"), "/")
	if len(parts) != 4 {
		return nil, status.Errorf(codes.InvalidArgument, "invalid resource name %q: expected 4 path segments", name)
	}

	entity := &testdata.GetOnlyUser{}

	if parts[3] == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing id in resource name: %q", name)
	}
	entity.Id = parts[3]

	filter := h.primaryKeyFilter(entity)

	selectCols := []string{"id"}
	selQ := sqldialect.NewSelectQuery("get_only_user", selectCols, filter, nil, 1, 0, false)
	sqlStr, args, err := h.dialect.BuildSelect(selQ)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building select SQL: %v", err)
	}

	var checkPK0 string
	row := h.db.QueryRowContext(ctx, sqlStr, args...)
	if err := row.Scan(&checkPK0); err != nil {
		if err == sql.ErrNoRows {
			return nil, status.Errorf(codes.NotFound, "GetOnlyUser %q not found", name)
		}
		if strings.Contains(strings.ToLower(err.Error()), "permission denied") ||
			strings.Contains(strings.ToLower(err.Error()), "access denied") {
			return nil, status.Errorf(codes.PermissionDenied, "permission denied: %v", err)
		}
		return nil, status.Errorf(codes.Internal, "querying GetOnlyUser: %v", err)
	}

	return entity, nil
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *GetOnlyUserGetHandler) primaryKeyFilter(entity *testdata.GetOnlyUser) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Condition{
			Condition: &gocrudv1.Condition{
				Column:  "id",
				Op:      gocrudv1.Operator_EQUAL,
				Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetId())},
			},
		},
	}
}
