// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"database/sql"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/timestamppb"
	"strings"
	"time"
)

// CheckpointGetHandler handles Get requests for Checkpoint entities.
type CheckpointGetHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewCheckpointGetHandler creates a new handler for getting Checkpoint entities.
func NewCheckpointGetHandler(db DBExecutor, backend sqldialect.BackendType) (*CheckpointGetHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &CheckpointGetHandler{db: db, dialect: b}, nil
}

// Get handles a GetCheckpointRequest and returns the Checkpoint.
func (h *CheckpointGetHandler) Get(ctx context.Context, req *testdata.GetCheckpointRequest) (*testdata.Checkpoint, error) {
	name := req.GetName()
	if name == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing resource name")
	}

	parts := strings.Split(strings.TrimPrefix(name, "/"), "/")
	if len(parts) != 5 {
		return nil, status.Errorf(codes.InvalidArgument, "invalid resource name %q: expected 5 path segments", name)
	}

	entity := &testdata.Checkpoint{}

	if parts[3] == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing job_id in resource name: %q", name)
	}
	entity.JobId = parts[3]

	{
		t, err := time.Parse(time.RFC3339Nano, parts[4])
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid checkpoint_at in resource name: %v", err)
		}
		entity.CheckpointAt = timestamppb.New(t)
	}

	filter := h.primaryKeyFilter(entity)

	selectCols := []string{"label"}
	selQ := sqldialect.NewSelectQuery("checkpoint", selectCols, filter, nil, 1, 0, false)
	sqlStr, args, err := h.dialect.BuildSelect(selQ)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building select SQL: %v", err)
	}

	var scan0 string
	row := h.db.QueryRowContext(ctx, sqlStr, args...)
	if err := row.Scan(&scan0); err != nil {
		if err == sql.ErrNoRows {
			return nil, status.Errorf(codes.NotFound, "Checkpoint %q not found", name)
		}
		if strings.Contains(strings.ToLower(err.Error()), "permission denied") ||
			strings.Contains(strings.ToLower(err.Error()), "access denied") {
			return nil, status.Errorf(codes.PermissionDenied, "permission denied: %v", err)
		}
		return nil, status.Errorf(codes.Internal, "querying Checkpoint: %v", err)
	}

	entity.Label = scan0
	return entity, nil
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *CheckpointGetHandler) primaryKeyFilter(entity *testdata.Checkpoint) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Composite{
			Composite: &gocrudv1.CompositeFilter{
				Op: gocrudv1.CompositeFilter_AND,
				Filters: []*gocrudv1.Filter{
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "job_id",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetJobId())},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "checkpoint_at",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: timestampValue(entity.GetCheckpointAt())},
							},
						},
					},
				},
			},
		},
	}
}
