// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"database/sql"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/genproto/googleapis/type/date"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/timestamppb"
	"strconv"
	"strings"
	"time"
)

// AutogenUserGetHandler handles Get requests for AutogenUser entities.
type AutogenUserGetHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewAutogenUserGetHandler creates a new handler for getting AutogenUser entities.
func NewAutogenUserGetHandler(db DBExecutor, backend sqldialect.BackendType) (*AutogenUserGetHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &AutogenUserGetHandler{db: db, dialect: b}, nil
}

// Get handles a GetAutogenUserRequest and returns the AutogenUser.
func (h *AutogenUserGetHandler) Get(ctx context.Context, req *testdata.GetAutogenUserRequest) (*testdata.AutogenUser, error) {
	name := req.GetName()
	if name == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing resource name")
	}

	parts := strings.Split(strings.TrimPrefix(name, "/"), "/")
	if len(parts) != 6 {
		return nil, status.Errorf(codes.InvalidArgument, "invalid resource name %q: expected 6 path segments", name)
	}

	entity := &testdata.AutogenUser{}

	if parts[3] == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing id_1 in resource name: %q", name)
	}
	entity.Id_1 = parts[3]

	{
		v, err := strconv.ParseInt(parts[4], 10, 64)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid id_2 in resource name: %v", err)
		}
		entity.Id_2 = v
	}

	{
		v, err := strconv.ParseInt(parts[5], 10, 64)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid id_3 in resource name: %v", err)
		}
		entity.Id_3 = v
	}

	filter := h.primaryKeyFilter(entity)

	selectCols := []string{"email", "commit_timestamp", "date_of_birth"}
	selQ := sqldialect.NewSelectQuery("composite_entities", selectCols, filter, nil, 1, 0, false)
	sqlStr, args, err := h.dialect.BuildSelect(selQ)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building select SQL: %v", err)
	}

	var scan0 string
	var scan1 time.Time
	var scan2 time.Time
	row := h.db.QueryRowContext(ctx, sqlStr, args...)
	if err := row.Scan(&scan0, &scan1, &scan2); err != nil {
		if err == sql.ErrNoRows {
			return nil, status.Errorf(codes.NotFound, "AutogenUser %q not found", name)
		}
		if strings.Contains(strings.ToLower(err.Error()), "permission denied") ||
			strings.Contains(strings.ToLower(err.Error()), "access denied") {
			return nil, status.Errorf(codes.PermissionDenied, "permission denied: %v", err)
		}
		return nil, status.Errorf(codes.Internal, "querying AutogenUser: %v", err)
	}

	entity.Email = scan0
	entity.CommitTimestamp = timestamppb.New(scan1)
	entity.DateOfBirth = &date.Date{Year: int32(scan2.Year()), Month: int32(scan2.Month()), Day: int32(scan2.Day())}
	return entity, nil
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *AutogenUserGetHandler) primaryKeyFilter(entity *testdata.AutogenUser) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Composite{
			Composite: &gocrudv1.CompositeFilter{
				Op: gocrudv1.CompositeFilter_AND,
				Filters: []*gocrudv1.Filter{
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id_1",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetId_1())},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id_2",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: intValue(entity.GetId_2())},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id_3",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: intValue(entity.GetId_3())},
							},
						},
					},
				},
			},
		},
	}
}
