// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"github.com/FlorinBalint/gocrud/crud"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/genproto/googleapis/type/date"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/timestamppb"
	"time"
)

// AutogenUserListHandler handles List requests for AutogenUser entities.
type AutogenUserListHandler struct {
	db              DBExecutor
	dialect         sqldialect.Builder
	defaultPageSize int32
	maxPageSize     int32
}

// NewAutogenUserListHandler creates a new handler for listing AutogenUser entities.
func NewAutogenUserListHandler(db DBExecutor, backend sqldialect.BackendType, defaultPageSize, maxPageSize int32) (*AutogenUserListHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &AutogenUserListHandler{
		db:              db,
		dialect:         b,
		defaultPageSize: defaultPageSize,
		maxPageSize:     maxPageSize,
	}, nil
}

// List handles a ListAutogenUsersRequest and returns the matching AutogenUser entities.
func (h *AutogenUserListHandler) List(ctx context.Context, req *testdata.ListAutogenUsersRequest) (*testdata.ListAutogenUsersResponse, error) {
	qHash, err := crud.QueryHash(req.GetFilter(), req.GetOrderBy())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "hashing query: %v", err)
	}

	offset, pageSize, err := crud.ResolvePageParams(req.GetPagination(), qHash, h.defaultPageSize, h.maxPageSize)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	includeTotal := req.GetIncludeTotal()
	fetchLimit := pageSize
	if !includeTotal {
		fetchLimit = pageSize + 1
	}

	q := sqldialect.NewSelectQuery("composite_entities", nil, req.GetFilter(), req.GetOrderBy(), fetchLimit, offset, includeTotal)
	sqlStr, args, err := h.dialect.BuildSelect(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building SQL: %v", err)
	}

	sqlRows, err := h.db.QueryContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing query: %v", err)
	}
	defer sqlRows.Close()

	var items []*testdata.AutogenUser
	var totalSize int64
	for sqlRows.Next() {
		entity := &testdata.AutogenUser{}

		var scan0 string
		var scan1 int64
		var scan2 int64
		var scan3 string
		var scan4 time.Time
		var scan5 time.Time
		scanDests := []any{
			&scan0,
			&scan1,
			&scan2,
			&scan3,
			&scan4,
			&scan5,
		}
		if includeTotal {
			scanDests = append(scanDests, &totalSize)
		}
		if err := sqlRows.Scan(scanDests...); err != nil {
			return nil, status.Errorf(codes.Internal, "scanning row: %v", err)
		}

		entity.Id_1 = scan0
		entity.Id_2 = scan1
		entity.Id_3 = scan2
		entity.Email = scan3
		entity.CommitTimestamp = timestamppb.New(scan4)
		entity.DateOfBirth = &date.Date{Year: int32(scan5.Year()), Month: int32(scan5.Month()), Day: int32(scan5.Day())}
		items = append(items, entity)
	}
	if err := sqlRows.Err(); err != nil {
		return nil, status.Errorf(codes.Internal, "reading rows: %v", err)
	}

	var hasNext bool
	if includeTotal {
		hasNext = offset+int64(len(items)) < totalSize
	} else {
		hasNext = len(items) == int(pageSize)+1
		if hasNext {
			items = items[:len(items)-1]
		}
	}

	return &testdata.ListAutogenUsersResponse{
		AutogenUsers:  items,
		NextPageToken: crud.NextPageToken(offset, pageSize, hasNext, qHash),
		PrevPageToken: crud.PrevPageToken(offset, pageSize, qHash),
		TotalSize:     totalSize,
	}, nil
}
