// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"github.com/FlorinBalint/gocrud/crud"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// OptionsOverrideUserListHandler handles List requests for OptionsOverrideUser entities.
type OptionsOverrideUserListHandler struct {
	db              DBExecutor
	dialect         sqldialect.Builder
	defaultPageSize int32
	maxPageSize     int32
}

// NewOptionsOverrideUserListHandler creates a new handler for listing OptionsOverrideUser entities.
func NewOptionsOverrideUserListHandler(db DBExecutor, backend sqldialect.BackendType, defaultPageSize, maxPageSize int32) (*OptionsOverrideUserListHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &OptionsOverrideUserListHandler{
		db:              db,
		dialect:         b,
		defaultPageSize: defaultPageSize,
		maxPageSize:     maxPageSize,
	}, nil
}

// List handles a ListOptionsOverrideUsersRequest and returns the matching OptionsOverrideUser entities.
func (h *OptionsOverrideUserListHandler) List(ctx context.Context, req *testdata.ListOptionsOverrideUsersRequest) (*testdata.ListOptionsOverrideUsersResponse, error) {
	qHash, err := crud.QueryHash(req.GetFilter(), req.GetOrderBy())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "hashing query: %v", err)
	}

	offset, pageSize, err := crud.ResolvePageParams(req.GetPagination(), qHash, h.defaultPageSize, h.maxPageSize)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	includeTotal := req.GetIncludeTotal()
	fetchLimit := pageSize
	if !includeTotal {
		fetchLimit = pageSize + 1
	}

	q := sqldialect.NewSelectQuery("options_override_user", nil, req.GetFilter(), req.GetOrderBy(), fetchLimit, offset, includeTotal)
	sqlStr, args, err := h.dialect.BuildSelect(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building SQL: %v", err)
	}

	sqlRows, err := h.db.QueryContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing query: %v", err)
	}
	defer sqlRows.Close()

	var items []*testdata.OptionsOverrideUser
	var totalSize int64
	for sqlRows.Next() {
		entity := &testdata.OptionsOverrideUser{}

		var scan0 string
		var scan1 string
		scanDests := []any{
			&scan0,
			&scan1,
		}
		if includeTotal {
			scanDests = append(scanDests, &totalSize)
		}
		if err := sqlRows.Scan(scanDests...); err != nil {
			return nil, status.Errorf(codes.Internal, "scanning row: %v", err)
		}

		entity.AccountId = scan0
		entity.Id = scan1
		items = append(items, entity)
	}
	if err := sqlRows.Err(); err != nil {
		return nil, status.Errorf(codes.Internal, "reading rows: %v", err)
	}

	var hasNext bool
	if includeTotal {
		hasNext = offset+int64(len(items)) < totalSize
	} else {
		hasNext = len(items) == int(pageSize)+1
		if hasNext {
			items = items[:len(items)-1]
		}
	}

	return &testdata.ListOptionsOverrideUsersResponse{
		OptionsOverrideUsers: items,
		NextPageToken:        crud.NextPageToken(offset, pageSize, hasNext, qHash),
		PrevPageToken:        crud.PrevPageToken(offset, pageSize, qHash),
		TotalSize:            totalSize,
	}, nil
}
