// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"github.com/FlorinBalint/gocrud/crud"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ListUpsertDeleteWithEtagUserListHandler handles List requests for ListUpsertDeleteWithEtagUser entities.
type ListUpsertDeleteWithEtagUserListHandler struct {
	db              DBExecutor
	dialect         sqldialect.Builder
	defaultPageSize int32
	maxPageSize     int32
}

// NewListUpsertDeleteWithEtagUserListHandler creates a new handler for listing ListUpsertDeleteWithEtagUser entities.
func NewListUpsertDeleteWithEtagUserListHandler(db DBExecutor, backend sqldialect.BackendType, defaultPageSize, maxPageSize int32) (*ListUpsertDeleteWithEtagUserListHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &ListUpsertDeleteWithEtagUserListHandler{
		db:              db,
		dialect:         b,
		defaultPageSize: defaultPageSize,
		maxPageSize:     maxPageSize,
	}, nil
}

// List handles a ListListUpsertDeleteWithEtagUsersRequest and returns the matching ListUpsertDeleteWithEtagUser entities.
func (h *ListUpsertDeleteWithEtagUserListHandler) List(ctx context.Context, req *testdata.ListListUpsertDeleteWithEtagUsersRequest) (*testdata.ListListUpsertDeleteWithEtagUsersResponse, error) {
	qHash, err := crud.QueryHash(req.GetFilter(), req.GetOrderBy())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "hashing query: %v", err)
	}

	offset, pageSize, err := crud.ResolvePageParams(req.GetPagination(), qHash, h.defaultPageSize, h.maxPageSize)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	includeTotal := req.GetIncludeTotal()
	fetchLimit := pageSize
	if !includeTotal {
		fetchLimit = pageSize + 1
	}

	q := sqldialect.NewSelectQuery("list_upsert_delete_with_etag_user", nil, req.GetFilter(), req.GetOrderBy(), fetchLimit, offset, includeTotal)
	sqlStr, args, err := h.dialect.BuildSelect(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building SQL: %v", err)
	}

	sqlRows, err := h.db.QueryContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing query: %v", err)
	}
	defer sqlRows.Close()

	var items []*testdata.ListUpsertDeleteWithEtagUser
	var totalSize int64
	for sqlRows.Next() {
		entity := &testdata.ListUpsertDeleteWithEtagUser{}

		var scan0 string
		scanDests := []any{
			&scan0,
		}
		if includeTotal {
			scanDests = append(scanDests, &totalSize)
		}
		if err := sqlRows.Scan(scanDests...); err != nil {
			return nil, status.Errorf(codes.Internal, "scanning row: %v", err)
		}

		entity.Id = scan0
		items = append(items, entity)
	}
	if err := sqlRows.Err(); err != nil {
		return nil, status.Errorf(codes.Internal, "reading rows: %v", err)
	}

	var hasNext bool
	if includeTotal {
		hasNext = offset+int64(len(items)) < totalSize
	} else {
		hasNext = len(items) == int(pageSize)+1
		if hasNext {
			items = items[:len(items)-1]
		}
	}

	return &testdata.ListListUpsertDeleteWithEtagUsersResponse{
		ListUpsertDeleteWithEtagUsers: items,
		NextPageToken:                 crud.NextPageToken(offset, pageSize, hasNext, qHash),
		PrevPageToken:                 crud.PrevPageToken(offset, pageSize, qHash),
		TotalSize:                     totalSize,
	}, nil
}
