// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"github.com/FlorinBalint/gocrud/crud"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ListOnlyUserListHandler handles List requests for ListOnlyUser entities.
type ListOnlyUserListHandler struct {
	db              DBExecutor
	dialect         sqldialect.Builder
	defaultPageSize int32
	maxPageSize     int32
}

// NewListOnlyUserListHandler creates a new handler for listing ListOnlyUser entities.
func NewListOnlyUserListHandler(db DBExecutor, backend sqldialect.BackendType, defaultPageSize, maxPageSize int32) (*ListOnlyUserListHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &ListOnlyUserListHandler{
		db:              db,
		dialect:         b,
		defaultPageSize: defaultPageSize,
		maxPageSize:     maxPageSize,
	}, nil
}

// List handles a ListListOnlyUsersRequest and returns the matching ListOnlyUser entities.
func (h *ListOnlyUserListHandler) List(ctx context.Context, req *testdata.ListListOnlyUsersRequest) (*testdata.ListListOnlyUsersResponse, error) {
	qHash, err := crud.QueryHash(req.GetFilter(), req.GetOrderBy())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "hashing query: %v", err)
	}

	offset, pageSize, err := crud.ResolvePageParams(req.GetPagination(), qHash, h.defaultPageSize, h.maxPageSize)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	includeTotal := req.GetIncludeTotal()
	fetchLimit := pageSize
	if !includeTotal {
		fetchLimit = pageSize + 1
	}

	q := sqldialect.NewSelectQuery("list_only_user", nil, req.GetFilter(), req.GetOrderBy(), fetchLimit, offset, includeTotal)
	sqlStr, args, err := h.dialect.BuildSelect(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building SQL: %v", err)
	}

	sqlRows, err := h.db.QueryContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing query: %v", err)
	}
	defer sqlRows.Close()

	var items []*testdata.ListOnlyUser
	var totalSize int64
	for sqlRows.Next() {
		entity := &testdata.ListOnlyUser{}

		var scan0 string
		scanDests := []any{
			&scan0,
		}
		if includeTotal {
			scanDests = append(scanDests, &totalSize)
		}
		if err := sqlRows.Scan(scanDests...); err != nil {
			return nil, status.Errorf(codes.Internal, "scanning row: %v", err)
		}

		entity.Id = scan0
		items = append(items, entity)
	}
	if err := sqlRows.Err(); err != nil {
		return nil, status.Errorf(codes.Internal, "reading rows: %v", err)
	}

	var hasNext bool
	if includeTotal {
		hasNext = offset+int64(len(items)) < totalSize
	} else {
		hasNext = len(items) == int(pageSize)+1
		if hasNext {
			items = items[:len(items)-1]
		}
	}

	return &testdata.ListListOnlyUsersResponse{
		ListOnlyUsers: items,
		NextPageToken: crud.NextPageToken(offset, pageSize, hasNext, qHash),
		PrevPageToken: crud.PrevPageToken(offset, pageSize, qHash),
		TotalSize:     totalSize,
	}, nil
}
