// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"database/sql"

	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"google.golang.org/genproto/googleapis/type/date"
	"google.golang.org/genproto/googleapis/type/decimal"
	"google.golang.org/genproto/googleapis/type/timeofday"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// integer is a local constraint covering all Go integer types.
type integer interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64
}

// float is a local constraint covering all Go floating-point types.
type float interface {
	~float32 | ~float64
}

// DBExecutor is the interface for executing SQL queries.
// Satisfied by *sql.DB, *sql.Tx, and test mocks.
type DBExecutor interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

// txBeginner is an optional interface for DBExecutor to start transactions.
type txBeginner interface {
	BeginTx(context.Context, *sql.TxOptions) (*sql.Tx, error)
}

// runInTx executes the given function inside a transaction if db supports it.
// If db is already a transaction or a mock, it executes the function directly.
func runInTx(ctx context.Context, db DBExecutor, fn func(tx DBExecutor) error) error {
	if beginner, ok := db.(txBeginner); ok {
		tx, err := beginner.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		defer tx.Rollback()
		if err := fn(tx); err != nil {
			return err
		}
		return tx.Commit()
	}
	return fn(db)
}

// RowScanner is an interface matching the Scan method of sql.Row and sql.Rows.
type RowScanner interface {
	Scan(dest ...any) error
}

// execAndScan executes an insert or update query.
// If the dialect supports returning, it executes execSql and scans the result.
// Otherwise, it runs execSql and selSql sequentially within a transaction and scans the result of selSql.
func execAndScan(
	ctx context.Context,
	db DBExecutor,
	supportsReturning bool,
	execSql string, execArgs []any,
	selSql string, selArgs []any,
	scan func(RowScanner) error,
) error {
	if supportsReturning {
		return scan(db.QueryRowContext(ctx, execSql, execArgs...))
	}
	return runInTx(ctx, db, func(tx DBExecutor) error {
		if _, err := tx.ExecContext(ctx, execSql, execArgs...); err != nil {
			return err
		}
		if selSql != "" {
			return scan(tx.QueryRowContext(ctx, selSql, selArgs...))
		}
		return nil
	})
}

// execInsertAndScan executes an insert query.
// If the dialect supports returning, it executes execSql and scans the result.
// Otherwise, it runs execSql in a transaction, captures the LastInsertId if applicable,
// builds the select query using the provided buildSelect function, and scans the result.
func execInsertAndScan(
	ctx context.Context,
	db DBExecutor,
	supportsReturning bool,
	execSql string, execArgs []any,
	buildSelect func(lastInsertId int64) (string, []any, error),
	scan func(RowScanner) error,
) error {
	if supportsReturning {
		return scan(db.QueryRowContext(ctx, execSql, execArgs...))
	}
	return runInTx(ctx, db, func(tx DBExecutor) error {
		res, err := tx.ExecContext(ctx, execSql, execArgs...)
		if err != nil {
			return err
		}
		var id int64
		if res != nil {
			if lastId, err := res.LastInsertId(); err == nil && lastId > 0 {
				id = lastId
			}
		}
		selSql, selArgs, err := buildSelect(id)
		if err != nil {
			return err
		}
		if selSql != "" {
			return scan(tx.QueryRowContext(ctx, selSql, selArgs...))
		}
		return nil
	})
}

func intValue[T integer](i T) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_IntValue{IntValue: int64(i)}}
}

func doubleValue[T float](f T) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_DoubleValue{DoubleValue: float64(f)}}
}

func stringValue(s string) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_StringValue{StringValue: s}}
}

func boolValue(b bool) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_BoolValue{BoolValue: b}}
}

func bytesValue(b []byte) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_BytesValue{BytesValue: b}}
}

func timestampValue(t *timestamppb.Timestamp) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_TimestampValue{TimestampValue: t}}
}

func dateValue(d *date.Date) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_DateValue{DateValue: d}}
}

func timeOfDayValue(t *timeofday.TimeOfDay) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_TimeValue{TimeValue: t}}
}

func decimalValue(d *decimal.Decimal) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_DecimalValue{DecimalValue: d}}
}

func durationValue(d *durationpb.Duration) *gocrudv1.Value {
	return &gocrudv1.Value{Kind: &gocrudv1.Value_IntervalValue{IntervalValue: d}}
}
