// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"database/sql"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// OptionsOverrideUserUpdateHandler handles Update requests for OptionsOverrideUser entities.
type OptionsOverrideUserUpdateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewOptionsOverrideUserUpdateHandler creates a new handler for updating OptionsOverrideUser entities.
func NewOptionsOverrideUserUpdateHandler(db DBExecutor, backend sqldialect.BackendType) (*OptionsOverrideUserUpdateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &OptionsOverrideUserUpdateHandler{db: db, dialect: b}, nil
}

// Update handles an UpdateOptionsOverrideUserRequest and returns the updated OptionsOverrideUser.
func (h *OptionsOverrideUserUpdateHandler) Update(ctx context.Context, req *testdata.UpdateOptionsOverrideUserRequest) (*testdata.OptionsOverrideUser, error) {
	entity := req.GetOptionsOverrideUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing OptionsOverrideUser in request")
	}

	if err := h.validateKeys(entity); err != nil {
		return nil, err
	}

	mask, err := h.validateMask(req.GetUpdateMask().GetPaths())
	if err != nil {
		return nil, err
	}

	updates := h.buildColumnUpdates(entity, mask)
	if len(updates) == 0 {
		return entity, nil
	}

	sqlStr, args, err := h.buildUpdateSQL(entity, updates)
	if err != nil {
		return nil, err
	}

	var selSql string
	var selArgs []any
	if !h.dialect.SupportsReturning() {
		selSql, selArgs, err = h.buildSelectSQL(entity)
		if err != nil {
			return nil, err
		}
	}

	err = execAndScan(ctx, h.db, h.dialect.SupportsReturning(),
		sqlStr, args,
		selSql, selArgs,
		func(row RowScanner) error {
			return row.Scan()
		},
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, status.Errorf(codes.NotFound, "entity not found after update")
		}
		return nil, status.Errorf(codes.Internal, "executing update: %v", err)
	}

	return entity, nil
}

// buildUpdateSQL builds the UPDATE query, including RETURNING for all non-PK fields
// when the dialect supports it.
func (h *OptionsOverrideUserUpdateHandler) buildUpdateSQL(entity *testdata.OptionsOverrideUser, updates []*gocrudv1.ColumnUpdate) (string, []any, error) {
	filter := h.primaryKeyFilter(entity)
	var returningCols []string
	if h.dialect.SupportsReturning() {
		returningCols = []string{}
	}
	q := sqldialect.NewUpdateQuery("options_override_user", updates, filter, returningCols)
	sqlStr, args, err := h.dialect.BuildUpdate(q)
	if err != nil {
		return "", nil, status.Errorf(codes.Internal, "building update SQL: %v", err)
	}
	return sqlStr, args, nil
}

// buildSelectSQL builds a SELECT query to re-read all non-PK fields after a non-RETURNING update.
func (h *OptionsOverrideUserUpdateHandler) buildSelectSQL(entity *testdata.OptionsOverrideUser) (string, []any, error) {
	filter := h.primaryKeyFilter(entity)
	selectCols := []string{}
	selQ := sqldialect.NewSelectQuery("options_override_user", selectCols, filter, nil, 1, 0, false)
	sqlStr, args, err := h.dialect.BuildSelect(selQ)
	if err != nil {
		return "", nil, status.Errorf(codes.Internal, "building select SQL: %v", err)
	}
	return sqlStr, args, nil
}

// validateKeys checks that all primary key fields are populated on the entity.
func (h *OptionsOverrideUserUpdateHandler) validateKeys(entity *testdata.OptionsOverrideUser) error {
	if entity.GetAccountId() == "" {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: account_id")
	}
	if entity.GetId() == "" {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: id")
	}
	return nil
}

// validateMask validates the update_mask paths.
// An empty or wildcard-only ("*") mask returns nil (meaning update all fields).
// A wildcard combined with other paths is rejected.
// Primary key fields and unknown fields are rejected.
func (h *OptionsOverrideUserUpdateHandler) validateMask(paths []string) ([]string, error) {
	if len(paths) == 0 {
		return nil, nil
	}

	hasWildcard := false
	for _, p := range paths {
		if p == "*" {
			hasWildcard = true
			break
		}
	}
	if hasWildcard {
		if len(paths) > 1 {
			return nil, status.Errorf(codes.InvalidArgument, "update_mask with wildcard \"*\" must not contain other paths")
		}
		return nil, nil
	}

	allowedFields := map[string]bool{}
	for _, p := range paths {
		if !allowedFields[p] {
			if p == "account_id" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			if p == "id" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			return nil, status.Errorf(codes.InvalidArgument, "unknown field in update_mask: %q", p)
		}
	}
	return paths, nil
}

// buildColumnUpdates builds the list of column updates from the entity.
// If mask is nil, all updatable fields are included.
func (h *OptionsOverrideUserUpdateHandler) buildColumnUpdates(entity *testdata.OptionsOverrideUser, mask []string) []*gocrudv1.ColumnUpdate {
	var updates []*gocrudv1.ColumnUpdate
	return updates
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *OptionsOverrideUserUpdateHandler) primaryKeyFilter(entity *testdata.OptionsOverrideUser) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Composite{
			Composite: &gocrudv1.CompositeFilter{
				Op: gocrudv1.CompositeFilter_AND,
				Filters: []*gocrudv1.Filter{
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "account_id",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetAccountId())},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetId())},
							},
						},
					},
				},
			},
		},
	}
}
