// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"database/sql"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/genproto/googleapis/type/date"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/timestamppb"
	"time"
)

// AutogenUserUpdateHandler handles Update requests for AutogenUser entities.
type AutogenUserUpdateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewAutogenUserUpdateHandler creates a new handler for updating AutogenUser entities.
func NewAutogenUserUpdateHandler(db DBExecutor, backend sqldialect.BackendType) (*AutogenUserUpdateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &AutogenUserUpdateHandler{db: db, dialect: b}, nil
}

// Update handles an UpdateAutogenUserRequest and returns the updated AutogenUser.
func (h *AutogenUserUpdateHandler) Update(ctx context.Context, req *testdata.UpdateAutogenUserRequest) (*testdata.AutogenUser, error) {
	entity := req.GetAutogenUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing AutogenUser in request")
	}

	if err := h.validateKeys(entity); err != nil {
		return nil, err
	}

	mask, err := h.validateMask(req.GetUpdateMask().GetPaths())
	if err != nil {
		return nil, err
	}

	updates := h.buildColumnUpdates(entity, mask)
	if len(updates) == 0 {
		return entity, nil
	}

	sqlStr, args, err := h.buildUpdateSQL(entity, updates)
	if err != nil {
		return nil, err
	}

	var selSql string
	var selArgs []any
	if !h.dialect.SupportsReturning() {
		selSql, selArgs, err = h.buildSelectSQL(entity)
		if err != nil {
			return nil, err
		}
	}

	var scan0 string
	var scan1 time.Time
	var scan2 time.Time
	err = execAndScan(ctx, h.db, h.dialect.SupportsReturning(),
		sqlStr, args,
		selSql, selArgs,
		func(row RowScanner) error {
			return row.Scan(&scan0, &scan1, &scan2)
		},
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, status.Errorf(codes.NotFound, "entity not found after update")
		}
		return nil, status.Errorf(codes.Internal, "executing update: %v", err)
	}

	entity.Email = scan0
	entity.CommitTimestamp = timestamppb.New(scan1)
	entity.DateOfBirth = &date.Date{Year: int32(scan2.Year()), Month: int32(scan2.Month()), Day: int32(scan2.Day())}
	return entity, nil
}

// buildUpdateSQL builds the UPDATE query, including RETURNING for all non-PK fields
// when the dialect supports it.
func (h *AutogenUserUpdateHandler) buildUpdateSQL(entity *testdata.AutogenUser, updates []*gocrudv1.ColumnUpdate) (string, []any, error) {
	filter := h.primaryKeyFilter(entity)
	var returningCols []string
	if h.dialect.SupportsReturning() {
		returningCols = []string{"email", "commit_timestamp", "date_of_birth"}
	}
	q := sqldialect.NewUpdateQuery("composite_entities", updates, filter, returningCols)
	sqlStr, args, err := h.dialect.BuildUpdate(q)
	if err != nil {
		return "", nil, status.Errorf(codes.Internal, "building update SQL: %v", err)
	}
	return sqlStr, args, nil
}

// buildSelectSQL builds a SELECT query to re-read all non-PK fields after a non-RETURNING update.
func (h *AutogenUserUpdateHandler) buildSelectSQL(entity *testdata.AutogenUser) (string, []any, error) {
	filter := h.primaryKeyFilter(entity)
	selectCols := []string{"email", "commit_timestamp", "date_of_birth"}
	selQ := sqldialect.NewSelectQuery("composite_entities", selectCols, filter, nil, 1, 0, false)
	sqlStr, args, err := h.dialect.BuildSelect(selQ)
	if err != nil {
		return "", nil, status.Errorf(codes.Internal, "building select SQL: %v", err)
	}
	return sqlStr, args, nil
}

// validateKeys checks that all primary key fields are populated on the entity.
func (h *AutogenUserUpdateHandler) validateKeys(entity *testdata.AutogenUser) error {
	if entity.GetId_1() == "" {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: id_1")
	}
	if entity.GetId_2() == 0 {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: id_2")
	}
	if entity.GetId_3() == 0 {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: id_3")
	}
	return nil
}

// validateMask validates the update_mask paths.
// An empty or wildcard-only ("*") mask returns nil (meaning update all fields).
// A wildcard combined with other paths is rejected.
// Primary key fields and unknown fields are rejected.
func (h *AutogenUserUpdateHandler) validateMask(paths []string) ([]string, error) {
	if len(paths) == 0 {
		return nil, nil
	}

	hasWildcard := false
	for _, p := range paths {
		if p == "*" {
			hasWildcard = true
			break
		}
	}
	if hasWildcard {
		if len(paths) > 1 {
			return nil, status.Errorf(codes.InvalidArgument, "update_mask with wildcard \"*\" must not contain other paths")
		}
		return nil, nil
	}

	allowedFields := map[string]bool{
		"email":            true,
		"commit_timestamp": true,
		"date_of_birth":    true,
	}
	for _, p := range paths {
		if !allowedFields[p] {
			if p == "id_1" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			if p == "id_2" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			if p == "id_3" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			return nil, status.Errorf(codes.InvalidArgument, "unknown field in update_mask: %q", p)
		}
	}
	return paths, nil
}

// buildColumnUpdates builds the list of column updates from the entity.
// If mask is nil, all updatable fields are included.
func (h *AutogenUserUpdateHandler) buildColumnUpdates(entity *testdata.AutogenUser, mask []string) []*gocrudv1.ColumnUpdate {
	updateAll := len(mask) == 0
	maskSet := make(map[string]bool, len(mask))
	for _, p := range mask {
		maskSet[p] = true
	}
	var updates []*gocrudv1.ColumnUpdate
	if updateAll || maskSet["email"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "email",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: stringValue(entity.GetEmail()),
			},
		})
	}
	if updateAll || maskSet["commit_timestamp"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "commit_timestamp",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: timestampValue(entity.GetCommitTimestamp()),
			},
		})
	}
	if updateAll || maskSet["date_of_birth"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "date_of_birth",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: dateValue(entity.GetDateOfBirth()),
			},
		})
	}
	return updates
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *AutogenUserUpdateHandler) primaryKeyFilter(entity *testdata.AutogenUser) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Composite{
			Composite: &gocrudv1.CompositeFilter{
				Op: gocrudv1.CompositeFilter_AND,
				Filters: []*gocrudv1.Filter{
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id_1",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetId_1())},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id_2",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: intValue(entity.GetId_2())},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column:  "id_3",
								Op:      gocrudv1.Operator_EQUAL,
								Operand: &gocrudv1.Condition_Value{Value: intValue(entity.GetId_3())},
							},
						},
					},
				},
			},
		},
	}
}
