// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"

	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// RealUserUpdateHandler handles Update requests for RealUser entities.
type RealUserUpdateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewRealUserUpdateHandler creates a new handler for updating RealUser entities.
func NewRealUserUpdateHandler(db DBExecutor, backend sqldialect.BackendType) (*RealUserUpdateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &RealUserUpdateHandler{db: db, dialect: b}, nil
}

// Update handles an UpdateRealUserRequest and returns the updated RealUser.
func (h *RealUserUpdateHandler) Update(ctx context.Context, req *testdata.UpdateRealUserRequest) (*testdata.RealUser, error) {
	entity := req.GetRealUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing RealUser in request")
	}

	if err := h.validateKeys(entity); err != nil {
		return nil, err
	}

	mask, err := h.validateMask(req.GetUpdateMask().GetPaths())
	if err != nil {
		return nil, err
	}

	updates := h.buildColumnUpdates(entity, mask)
	if len(updates) == 0 {
		return entity, nil
	}

	filter := h.primaryKeyFilter(entity)

	q := sqldialect.NewUpdateQuery("real_user", updates, filter)
	sqlStr, args, err := h.dialect.BuildUpdate(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building update SQL: %v", err)
	}

	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing update: %v", err)
	}

	return entity, nil
}

// validateKeys checks that all primary key fields are populated on the entity.
func (h *RealUserUpdateHandler) validateKeys(entity *testdata.RealUser) error {
	if entity.GetId() == "" {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: id")
	}
	return nil
}

// validateMask validates the update_mask paths.
// An empty or wildcard-only ("*") mask returns nil (meaning update all fields).
// A wildcard combined with other paths is rejected.
// Primary key fields and unknown fields are rejected.
func (h *RealUserUpdateHandler) validateMask(paths []string) ([]string, error) {
	if len(paths) == 0 {
		return nil, nil
	}

	hasWildcard := false
	for _, p := range paths {
		if p == "*" {
			hasWildcard = true
			break
		}
	}
	if hasWildcard {
		if len(paths) > 1 {
			return nil, status.Errorf(codes.InvalidArgument, "update_mask with wildcard \"*\" must not contain other paths")
		}
		return nil, nil
	}

	allowedFields := map[string]bool{
		"email": true,
	}
	for _, p := range paths {
		if !allowedFields[p] {
			if p == "id" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			return nil, status.Errorf(codes.InvalidArgument, "unknown field in update_mask: %q", p)
		}
	}
	return paths, nil
}

// buildColumnUpdates builds the list of column updates from the entity.
// If mask is nil, all updatable fields are included.
func (h *RealUserUpdateHandler) buildColumnUpdates(entity *testdata.RealUser, mask []string) []*gocrudv1.ColumnUpdate {
	updateAll := len(mask) == 0
	maskSet := make(map[string]bool, len(mask))
	for _, p := range mask {
		maskSet[p] = true
	}

	var updates []*gocrudv1.ColumnUpdate
	if updateAll || maskSet["email"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "email",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: &gocrudv1.Value{Kind: &gocrudv1.Value_StringValue{StringValue: entity.GetEmail()}},
			},
		})
	}
	return updates
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *RealUserUpdateHandler) primaryKeyFilter(entity *testdata.RealUser) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Condition{
			Condition: &gocrudv1.Condition{
				Column: "id",
				Op:     gocrudv1.Operator_EQUAL,
				Value:  &gocrudv1.Value{Kind: &gocrudv1.Value_StringValue{StringValue: entity.GetId()}},
			},
		},
	}
}
