// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"

	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// AutogenUserUpdateHandler handles Update requests for AutogenUser entities.
type AutogenUserUpdateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewAutogenUserUpdateHandler creates a new handler for updating AutogenUser entities.
func NewAutogenUserUpdateHandler(db DBExecutor, backend sqldialect.BackendType) (*AutogenUserUpdateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &AutogenUserUpdateHandler{db: db, dialect: b}, nil
}

// Update handles an UpdateAutogenUserRequest and returns the updated AutogenUser.
func (h *AutogenUserUpdateHandler) Update(ctx context.Context, req *testdata.UpdateAutogenUserRequest) (*testdata.AutogenUser, error) {
	entity := req.GetAutogenUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing AutogenUser in request")
	}

	if err := h.validateKeys(entity); err != nil {
		return nil, err
	}

	mask, err := h.validateMask(req.GetUpdateMask().GetPaths())
	if err != nil {
		return nil, err
	}

	updates := h.buildColumnUpdates(entity, mask)
	if len(updates) == 0 {
		return entity, nil
	}

	filter := h.primaryKeyFilter(entity)

	q := sqldialect.NewUpdateQuery("composite_entities", updates, filter)
	sqlStr, args, err := h.dialect.BuildUpdate(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building update SQL: %v", err)
	}

	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing update: %v", err)
	}

	return entity, nil
}

// validateKeys checks that all primary key fields are populated on the entity.
func (h *AutogenUserUpdateHandler) validateKeys(entity *testdata.AutogenUser) error {
	if entity.GetId_1() == "" {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: id_1")
	}
	if entity.GetId_2() == 0 {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: id_2")
	}
	if entity.GetId_3() == 0 {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: id_3")
	}
	return nil
}

// validateMask validates the update_mask paths.
// An empty or wildcard-only ("*") mask returns nil (meaning update all fields).
// A wildcard combined with other paths is rejected.
// Primary key fields and unknown fields are rejected.
func (h *AutogenUserUpdateHandler) validateMask(paths []string) ([]string, error) {
	if len(paths) == 0 {
		return nil, nil
	}

	hasWildcard := false
	for _, p := range paths {
		if p == "*" {
			hasWildcard = true
			break
		}
	}
	if hasWildcard {
		if len(paths) > 1 {
			return nil, status.Errorf(codes.InvalidArgument, "update_mask with wildcard \"*\" must not contain other paths")
		}
		return nil, nil
	}

	allowedFields := map[string]bool{
		"email": true,
	}
	for _, p := range paths {
		if !allowedFields[p] {
			if p == "id_1" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			if p == "id_2" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			if p == "id_3" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			return nil, status.Errorf(codes.InvalidArgument, "unknown field in update_mask: %q", p)
		}
	}
	return paths, nil
}

// buildColumnUpdates builds the list of column updates from the entity.
// If mask is nil, all updatable fields are included.
func (h *AutogenUserUpdateHandler) buildColumnUpdates(entity *testdata.AutogenUser, mask []string) []*gocrudv1.ColumnUpdate {
	updateAll := len(mask) == 0
	maskSet := make(map[string]bool, len(mask))
	for _, p := range mask {
		maskSet[p] = true
	}

	var updates []*gocrudv1.ColumnUpdate
	if updateAll || maskSet["email"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "email",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: &gocrudv1.Value{Kind: &gocrudv1.Value_StringValue{StringValue: entity.GetEmail()}},
			},
		})
	}
	return updates
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *AutogenUserUpdateHandler) primaryKeyFilter(entity *testdata.AutogenUser) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Composite{
			Composite: &gocrudv1.CompositeFilter{
				Op: gocrudv1.CompositeFilter_AND,
				Filters: []*gocrudv1.Filter{
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column: "id_1",
								Op:     gocrudv1.Operator_EQUAL,
								Value:  &gocrudv1.Value{Kind: &gocrudv1.Value_StringValue{StringValue: entity.GetId_1()}},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column: "id_2",
								Op:     gocrudv1.Operator_EQUAL,
								Value:  &gocrudv1.Value{Kind: &gocrudv1.Value_IntValue{IntValue: int64(entity.GetId_2())}},
							},
						},
					},
					{
						Filter: &gocrudv1.Filter_Condition{
							Condition: &gocrudv1.Condition{
								Column: "id_3",
								Op:     gocrudv1.Operator_EQUAL,
								Value:  &gocrudv1.Value{Kind: &gocrudv1.Value_IntValue{IntValue: int64(entity.GetId_3())}},
							},
						},
					},
				},
			},
		},
	}
}
