// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	"database/sql"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/genproto/googleapis/type/decimal"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/timestamppb"
	"time"
)

// ProductUpdateHandler handles Update requests for Product entities.
type ProductUpdateHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewProductUpdateHandler creates a new handler for updating Product entities.
func NewProductUpdateHandler(db DBExecutor, backend sqldialect.BackendType) (*ProductUpdateHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &ProductUpdateHandler{db: db, dialect: b}, nil
}

// Update handles an UpdateProductRequest and returns the updated Product.
func (h *ProductUpdateHandler) Update(ctx context.Context, req *testdata.UpdateProductRequest) (*testdata.Product, error) {
	entity := req.GetProduct()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing Product in request")
	}

	if err := h.validateKeys(entity); err != nil {
		return nil, err
	}

	mask, err := h.validateMask(req.GetUpdateMask().GetPaths())
	if err != nil {
		return nil, err
	}

	updates := h.buildColumnUpdates(entity, mask)
	if len(updates) == 0 {
		return entity, nil
	}

	sqlStr, args, err := h.buildUpdateSQL(entity, updates)
	if err != nil {
		return nil, err
	}

	var selSql string
	var selArgs []any
	if !h.dialect.SupportsReturning() {
		selSql, selArgs, err = h.buildSelectSQL(entity)
		if err != nil {
			return nil, err
		}
	}

	var scan0 string
	var scan1 string
	var scan2 string
	var scan3 int64
	var scan4 bool
	var scan5 time.Time
	err = execAndScan(ctx, h.db, h.dialect.SupportsReturning(),
		sqlStr, args,
		selSql, selArgs,
		func(row RowScanner) error {
			return row.Scan(&scan0, &scan1, &scan2, &scan3, &scan4, &scan5)
		},
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, status.Errorf(codes.NotFound, "entity not found after update")
		}
		return nil, status.Errorf(codes.Internal, "executing update: %v", err)
	}

	entity.Name = scan0
	entity.Description = scan1
	entity.Price = &decimal.Decimal{Value: scan2}
	entity.Quantity = int32(scan3)
	entity.Available = scan4
	entity.UpdatedAt = timestamppb.New(scan5)
	return entity, nil
}

// buildUpdateSQL builds the UPDATE query, including RETURNING for all non-PK fields
// when the dialect supports it.
func (h *ProductUpdateHandler) buildUpdateSQL(entity *testdata.Product, updates []*gocrudv1.ColumnUpdate) (string, []any, error) {
	filter := h.primaryKeyFilter(entity)
	var returningCols []string
	if h.dialect.SupportsReturning() {
		returningCols = []string{"name", "description", "price", "quantity", "available", "updated_at"}
	}
	q := sqldialect.NewUpdateQuery("product", updates, filter, returningCols)
	sqlStr, args, err := h.dialect.BuildUpdate(q)
	if err != nil {
		return "", nil, status.Errorf(codes.Internal, "building update SQL: %v", err)
	}
	return sqlStr, args, nil
}

// buildSelectSQL builds a SELECT query to re-read all non-PK fields after a non-RETURNING update.
func (h *ProductUpdateHandler) buildSelectSQL(entity *testdata.Product) (string, []any, error) {
	filter := h.primaryKeyFilter(entity)
	selectCols := []string{"name", "description", "price", "quantity", "available", "updated_at"}
	selQ := sqldialect.NewSelectQuery("product", selectCols, filter, nil, 1, 0, false)
	sqlStr, args, err := h.dialect.BuildSelect(selQ)
	if err != nil {
		return "", nil, status.Errorf(codes.Internal, "building select SQL: %v", err)
	}
	return sqlStr, args, nil
}

// validateKeys checks that all primary key fields are populated on the entity.
func (h *ProductUpdateHandler) validateKeys(entity *testdata.Product) error {
	if entity.GetId() == "" {
		return status.Errorf(codes.InvalidArgument, "missing required primary key field: id")
	}
	return nil
}

// validateMask validates the update_mask paths.
// An empty or wildcard-only ("*") mask returns nil (meaning update all fields).
// A wildcard combined with other paths is rejected.
// Primary key fields and unknown fields are rejected.
func (h *ProductUpdateHandler) validateMask(paths []string) ([]string, error) {
	if len(paths) == 0 {
		return nil, nil
	}

	hasWildcard := false
	for _, p := range paths {
		if p == "*" {
			hasWildcard = true
			break
		}
	}
	if hasWildcard {
		if len(paths) > 1 {
			return nil, status.Errorf(codes.InvalidArgument, "update_mask with wildcard \"*\" must not contain other paths")
		}
		return nil, nil
	}

	allowedFields := map[string]bool{
		"name":        true,
		"description": true,
		"price":       true,
		"quantity":    true,
		"available":   true,
		"updated_at":  true,
	}
	for _, p := range paths {
		if !allowedFields[p] {
			if p == "id" {
				return nil, status.Errorf(codes.InvalidArgument, "primary key field %q cannot be in update_mask", p)
			}
			return nil, status.Errorf(codes.InvalidArgument, "unknown field in update_mask: %q", p)
		}
	}
	return paths, nil
}

// buildColumnUpdates builds the list of column updates from the entity.
// If mask is nil, all updatable fields are included.
func (h *ProductUpdateHandler) buildColumnUpdates(entity *testdata.Product, mask []string) []*gocrudv1.ColumnUpdate {
	updateAll := len(mask) == 0
	maskSet := make(map[string]bool, len(mask))
	for _, p := range mask {
		maskSet[p] = true
	}
	var updates []*gocrudv1.ColumnUpdate
	if updateAll || maskSet["name"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "name",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: stringValue(entity.GetName()),
			},
		})
	}
	if updateAll || maskSet["description"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "description",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: stringValue(entity.GetDescription()),
			},
		})
	}
	if updateAll || maskSet["price"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "price",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: decimalValue(entity.GetPrice()),
			},
		})
	}
	if updateAll || maskSet["quantity"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "quantity",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: intValue(entity.GetQuantity()),
			},
		})
	}
	if updateAll || maskSet["available"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "available",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: boolValue(entity.GetAvailable()),
			},
		})
	}
	if updateAll || maskSet["updated_at"] {
		updates = append(updates, &gocrudv1.ColumnUpdate{
			Column: "updated_at",
			Assignment: &gocrudv1.ColumnUpdate_Value{
				Value: timestampValue(entity.GetUpdatedAt()),
			},
		})
	}
	return updates
}

// primaryKeyFilter builds a WHERE filter matching all primary key fields.
func (h *ProductUpdateHandler) primaryKeyFilter(entity *testdata.Product) *gocrudv1.Filter {
	return &gocrudv1.Filter{
		Filter: &gocrudv1.Filter_Condition{
			Condition: &gocrudv1.Condition{
				Column:  "id",
				Op:      gocrudv1.Operator_EQUAL,
				Operand: &gocrudv1.Condition_Value{Value: stringValue(entity.GetId())},
			},
		},
	}
}
