// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// RealUserUpsertHandler handles Upsert requests for RealUser entities.
type RealUserUpsertHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewRealUserUpsertHandler creates a new handler for upserting RealUser entities.
func NewRealUserUpsertHandler(db DBExecutor, backend sqldialect.BackendType) (*RealUserUpsertHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &RealUserUpsertHandler{db: db, dialect: b}, nil
}

// Upsert handles an UpsertRealUserRequest and returns the upserted RealUser.
func (h *RealUserUpsertHandler) Upsert(ctx context.Context, req *testdata.UpsertRealUserRequest) (*testdata.RealUser, error) {
	entity := req.GetRealUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing RealUser in request")
	}

	// Validate all primary key fields are populated.
	if entity.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required primary key field: id")
	}

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"id", "email"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetId()),
		stringValue(entity.GetEmail()),
	}
	conflictCols := []string{"id"}
	var returningCols []string
	q := sqldialect.NewUpsertQuery("real_user", columns, values, conflictCols, returningCols)
	sqlStr, args, err := h.dialect.BuildUpsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building upsert SQL: %v", err)
	}
	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing upsert: %v", err)
	}
	return entity, nil
}
