// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ListUpsertDeleteWithEtagUserUpsertHandler handles Upsert requests for ListUpsertDeleteWithEtagUser entities.
type ListUpsertDeleteWithEtagUserUpsertHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewListUpsertDeleteWithEtagUserUpsertHandler creates a new handler for upserting ListUpsertDeleteWithEtagUser entities.
func NewListUpsertDeleteWithEtagUserUpsertHandler(db DBExecutor, backend sqldialect.BackendType) (*ListUpsertDeleteWithEtagUserUpsertHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &ListUpsertDeleteWithEtagUserUpsertHandler{db: db, dialect: b}, nil
}

// Upsert handles an UpsertListUpsertDeleteWithEtagUserRequest and returns the upserted ListUpsertDeleteWithEtagUser.
func (h *ListUpsertDeleteWithEtagUserUpsertHandler) Upsert(ctx context.Context, req *testdata.UpsertListUpsertDeleteWithEtagUserRequest) (*testdata.ListUpsertDeleteWithEtagUser, error) {
	entity := req.GetListUpsertDeleteWithEtagUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing ListUpsertDeleteWithEtagUser in request")
	}

	// Validate all primary key fields are populated.
	if entity.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required primary key field: id")
	}

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"id"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetId()),
	}
	conflictCols := []string{"id"}
	var returningCols []string
	q := sqldialect.NewUpsertQuery("list_upsert_delete_with_etag_user", columns, values, conflictCols, returningCols)
	sqlStr, args, err := h.dialect.BuildUpsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building upsert SQL: %v", err)
	}
	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing upsert: %v", err)
	}
	return entity, nil
}
