// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// OptionsOverrideUserUpsertHandler handles Upsert requests for OptionsOverrideUser entities.
type OptionsOverrideUserUpsertHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewOptionsOverrideUserUpsertHandler creates a new handler for upserting OptionsOverrideUser entities.
func NewOptionsOverrideUserUpsertHandler(db DBExecutor, backend sqldialect.BackendType) (*OptionsOverrideUserUpsertHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &OptionsOverrideUserUpsertHandler{db: db, dialect: b}, nil
}

// Upsert handles an UpsertOptionsOverrideUserRequest and returns the upserted OptionsOverrideUser.
func (h *OptionsOverrideUserUpsertHandler) Upsert(ctx context.Context, req *testdata.UpsertOptionsOverrideUserRequest) (*testdata.OptionsOverrideUser, error) {
	entity := req.GetOptionsOverrideUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing OptionsOverrideUser in request")
	}

	// Validate all primary key fields are populated.
	if entity.GetAccountId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required primary key field: account_id")
	}
	if entity.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required primary key field: id")
	}

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"account_id", "id"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetAccountId()),
		stringValue(entity.GetId()),
	}
	conflictCols := []string{"account_id", "id"}
	var returningCols []string
	q := sqldialect.NewUpsertQuery("options_override_user", columns, values, conflictCols, returningCols)
	sqlStr, args, err := h.dialect.BuildUpsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building upsert SQL: %v", err)
	}
	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing upsert: %v", err)
	}
	return entity, nil
}
