// Code generated by handlersgen. DO NOT EDIT.

package handlers

import (
	"context"
	testdata "github.com/FlorinBalint/gocrud/entitygen/testdata"
	gocrudv1 "github.com/FlorinBalint/gocrud/proto/v1"
	"github.com/FlorinBalint/gocrud/sqldialect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// UpsertOnlyUserUpsertHandler handles Upsert requests for UpsertOnlyUser entities.
type UpsertOnlyUserUpsertHandler struct {
	db      DBExecutor
	dialect sqldialect.Builder
}

// NewUpsertOnlyUserUpsertHandler creates a new handler for upserting UpsertOnlyUser entities.
func NewUpsertOnlyUserUpsertHandler(db DBExecutor, backend sqldialect.BackendType) (*UpsertOnlyUserUpsertHandler, error) {
	b, err := sqldialect.ForBackend(backend)
	if err != nil {
		return nil, err
	}
	return &UpsertOnlyUserUpsertHandler{db: db, dialect: b}, nil
}

// Upsert handles an UpsertUpsertOnlyUserRequest and returns the upserted UpsertOnlyUser.
func (h *UpsertOnlyUserUpsertHandler) Upsert(ctx context.Context, req *testdata.UpsertUpsertOnlyUserRequest) (*testdata.UpsertOnlyUser, error) {
	entity := req.GetUpsertOnlyUser()
	if entity == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing UpsertOnlyUser in request")
	}

	// Validate all primary key fields are populated.
	if entity.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "missing required primary key field: id")
	}

	// Build INSERT values for non-auto-generated fields.
	columns := []string{"id"}
	values := []*gocrudv1.Value{
		stringValue(entity.GetId()),
	}
	conflictCols := []string{"id"}
	var returningCols []string
	q := sqldialect.NewUpsertQuery("upsert_only_user", columns, values, conflictCols, returningCols)
	sqlStr, args, err := h.dialect.BuildUpsert(q)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "building upsert SQL: %v", err)
	}
	_, err = h.db.ExecContext(ctx, sqlStr, args...)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "executing upsert: %v", err)
	}
	return entity, nil
}
